condense_wildcard_suffixes = true
format_strings             = true
imports_granularity        = "Crate"
imports_indent             = "Block"
imports_layout             = "Vertical"
normalize_comments         = true
reorder_imports            = true
use_try_shorthand          = true
chain_width                = 50
fn_single_line             = true
force_multiline_blocks     = true
max_width                  = 80